version: '3.8'

services:
    app:
        build: .
        container_name: symfony_app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/symfony
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: symfony_sortirentreamis
        environment:
            MYSQL_DATABASE: sortirentreamis
            MYSQL_USER: root
            MYSQL_PASSWORD: ''
            MYSQL_ROOT_PASSWORD: root1234
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql:rw

volumes:
    db_data:
